/*
TILEDATA.JS
A data object to return information about various types of structure.
*/
var tileData = {
  'boulder': {
    tag: 'boulder',
    name: "Boulder",
    description: "It's a boulder. You could probably get it out of the way if you built a Destroyer.",
    pipeable: false,
    rootable: false,
    builds: false,
  },
  'deposit': {
    tag: 'deposit',
    name: "Energy Deposit",
    description: "A naturally occuring energy deposit. You can build a Extractor on an adjacent tile to extract energy from it until it runs out.",
    pipeable: false,
    rootable: false,
    builds: false,
  },
  'destroyer': {
    tag: 'destroyer',
    name: "Destroyer",
    description: "A giant stationary plasma-cannon. It's based on one of the old models used in the great Human Wars.",
    pipeable: true,
    rootable: false,
    builds: false,
  },
  'empty': {
    tag: 'empty',
    name: "Empty",
    description: "",
    pipeable: false,
    rootable: false,
    builds: false,
  },
  'extractor': {
    tag: 'deposit',
    name: "Extractor",
    description: "An automated salvage and resource extraction center.",
    pipeable: true,
    rootable: false,
    builds: ['pipe'],
  },
  'pipe': {
    tag: 'pipe',
    name: "Pipe",
    description: "Compact insulated tubing to allow easy transmission of power and supplies across the arctic floor.",
    pipeable: true,
    rootable: false,
    builds: false,
  },
  'plasma': {
    tag: 'plasma',
    name: "Plasma",
    description: "",
    pipeable: false,
    rootable: false,
    builds: false,
  },
  'powerplant': {
    tag: 'powerplant',
    name: "Power Plant",
    description: "This is you. You're the AI controller of a miniature nuclear reactor. Anything that needs power needs to be connected to you by a pipe.",
    pipeable: true,
    rootable: false,
    builds: ['pipe', 'extractor', 'destroyer', 'researchStation'],
  },
  'researchStation': {
    tag: 'researchStation',
    name: "Research Station",
    description: "An advanced artificial intelligence scientific research station.",
    pipeable: true,
    rootable: false,
    builds: ['pipe', 'extractor'],
  },
  'root': {
    tag: 'root',
    name: "Root",
    description: "",
    pipeable: false,
    rootable: true,
    builds: false,
  },
  'rootflower': {
    tag: 'rootflower',
    name: "Rootflower",
    description: "The hub of a fast-growing invasive species from the south with no natural predators in the tundra.",
    pipeable: false,
    rootable: true,
    builds: false,
  },
  'sea': {
    tag: 'sea',
    name: "Sea",
    description: "",
    pipeable: false,
    rootable: false,
    builds: false,
  },
  'strangler': {
    tag: 'strangler',
    name: "Strangler",
    description: "It's a strangling root. It can apply sixteen times the constricting force of an Indian Python.",
    pipeable: true,
    rootable: true,
    builds: false,
  },
};
